---
- name: config tomcat
  hosts: all
  tasks: 
    - name: install tomcat9
      apt:
        name: tomcat9
        state: present
    - name: tomcat9_admin
      apt: 
        name: tomcat9-admin
        state: present
    - name: copy tomcat-users.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: change port 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: restart tomcat
      service:
        name: tomcat9
        state: restarted
    - name: pause for 1 min
      pause:
        minutes: 1
    - name: check server 1
      uri: 
        url: http://172.31.23.136:9090
        status_code: 200
    - name: check server 2
      uri:
        url: http://172.31.18.126:9090
        status_code: 200

...          
      
              
