---
- name: crate users & file/dir in home dir
  hosts: all
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create file/dir
      file:
        name: "{{d}}"
        state: "{{e}}"

...          
